import { existsSync, readFileSync, writeFileSync } from "node:fs";

// Files bundled into llms-full.txt, in order. Keep in sync with the public surface.
// NOTE: src/react/index.ts is auto-included when the ./react entry ships (it does).
const files = [
  "README.md",
  "CHANGELOG.md",
  "docs/API.md",
  "src/shared.ts",
  "src/client/types.ts",
  "src/client/index.ts",
  "src/component/schema.ts",
  "src/component/validators.ts",
  "src/component/mutations.ts",
  "src/component/queries.ts",
  "src/test.ts",
];

// Include react layer only when shipped (hooks-only -> .ts; .tsx if it renders)
const reactEntry = ["src/react/index.ts", "src/react/index.tsx"].find(existsSync);
if (reactEntry !== undefined) {
  files.push(reactEntry);
}

const PLANNED_BANNER =
  "NOTE: The released 0.1.0 API is the cache core (put, get, getByIsrc, invalidate, " +
  "pruneExpired, stats). The catalog engine — provider adapters (Spotify/Apple/Deezer/" +
  "MusicBrainz/Wikidata), read-through fetch, import/sync, and the [planned] React hooks — " +
  "is built on this branch but NOT yet in a stable release. Treat [planned] symbols as " +
  "unreleased (built, not absent); do not assume they ship in an installed 0.1.0.\n\n";

let out = `# @vllnt/convex-music — Full Source\n\nAuto-generated by \`pnpm generate:llms\`. Do not edit manually.\n`;

for (const f of files) {
  out += `\n---\n\n## ${f}\n\n`;
  if (f.endsWith(".md")) {
    const content = readFileSync(f, "utf8");
    // Prepend a banner to the README section so agents don't treat [planned] as real
    if (f === "README.md") {
      out += PLANNED_BANNER;
    }
    out += content;
  } else {
    out += "```ts\n" + readFileSync(f, "utf8") + "\n```";
  }
  out += "\n";
}

writeFileSync("llms-full.txt", out);
console.log(`Wrote llms-full.txt (${files.length} files)`);
