import { existsSync, readFileSync, writeFileSync } from "node:fs";

// Files bundled into llms-full.txt, in order. Keep in sync with the public surface.
// NOTE: src/react/index.tsx is included only when the ./react entry ships.
const files = [
  "README.md",
  "CHANGELOG.md",
  "docs/API.md",
  "src/shared.ts",
  "src/client/types.ts",
  "src/client/index.ts",
  "src/component/schema.ts",
  "src/component/validators.ts",
  "src/component/mutations.ts",
  "src/component/queries.ts",
  "src/test.ts",
];

// Include react layer only when shipped
const reactEntry = "src/react/index.tsx";
if (existsSync(reactEntry)) {
  files.push(reactEntry);
}

const PLANNED_BANNER =
  "NOTE: This README contains [planned] sections that document the roadmap surface " +
  "not yet implemented in 0.1.0. The shipped 0.1.0 API is the cache core (put, get, " +
  "getByIsrc, invalidate, pruneExpired, stats). Provider fetch/search adapters and the " +
  "artist-image auto-sync policy are planned — planned symbols must not be treated as " +
  "implemented.\n\n";

let out = `# @vllnt/convex-music — Full Source\n\nAuto-generated by \`pnpm generate:llms\`. Do not edit manually.\n`;

for (const f of files) {
  out += `\n---\n\n## ${f}\n\n`;
  if (f.endsWith(".md")) {
    const content = readFileSync(f, "utf8");
    // Prepend a banner to the README section so agents don't treat [planned] as real
    if (f === "README.md") {
      out += PLANNED_BANNER;
    }
    out += content;
  } else {
    out += "```ts\n" + readFileSync(f, "utf8") + "\n```";
  }
  out += "\n";
}

writeFileSync("llms-full.txt", out);
console.log(`Wrote llms-full.txt (${files.length} files)`);
